/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        theme: {
          deep: '#070609',
          surface: '#0c0b12',
          elevated: '#13111b',
          overlay: 'rgba(12, 11, 18, 0.85)',
          white: '#f5f4f8',
          'white-soft': '#c5c3d0',
          'text-muted': '#8b8899',
          'text-dim': '#5c596b',
          line: '#282533',
          'line-soft': '#1c1a24',
          'line-bright': '#3d394d',
          violet: '#7a4ee0',
          'violet-core': '#7a4ee0',
          'violet-ambient': '#351c68',
          'violet-highlight': '#bfa5ff',
          'violet-soft': 'rgba(122, 78, 224, 0.25)',
          'violet-faint': 'rgba(122, 78, 224, 0.10)',
          green: '#9eea9a',
          'green-soft': 'rgba(158, 234, 154, 0.20)',
          pill: '#ffffff',
          'pill-text': '#0b0a10',
          'pill-hover': '#ece9f5',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
        headline: [
          '"Helvetica Neue"',
          'Inter',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        mono: [
          '"IBM Plex Mono"',
          '"SFMono-Regular"',
          'Consolas',
          'Menlo',
          'Monaco',
          'monospace',
        ],
      },
      boxShadow: {
        'violet-glow': '0 0 50px -10px rgba(122, 78, 224, 0.35)',
        'violet-core': '0 0 100px 20px rgba(53, 28, 104, 0.5)',
        'hud-capsule': '0 8px 32px 0 rgba(0, 0, 0, 0.45)',
      },
    },
  },
  plugins: [],
};
